CREATE TABLE Users (
    ID INTEGER NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PersonalName VARCHAR(255) NOT NULL,
    FamilyName VARCHAR(255) NOT NULL,
    Role VARCHAR(255) NOT NULL,
    Team VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE Teams (
    TeamID INTEGER NOT NULL,
    TeamName VARCHAR(255) NOT NULL,
    CurrentProject VARCHAR(255) NOT NULL,
    Developers VARCHAR(255) NOT NULL,
    CEO VARCHAR(255) NOT NULL,
    PRIMARY KEY (TeamID)
);
CREATE TABLE Project (
    ProjectID INTEGER NOT NULL,
    ProjectName VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    CurrentTeam VARCHAR(255) NOT NULL,
    PRIMARY KEY (ProjectID)
);